// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth/auth.proto

package auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册请求
type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // 用户名
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                            // 密码
	PhoneNumber     string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                   // 手机号
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                                                  // 邮箱（可选）
	Gender          int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`                                               // 性别（可选）
	ChineseName     string                 `protobuf:"bytes,6,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`                   // 中文姓名（可选）
	WxMiniAppOpenId string                 `protobuf:"bytes,7,opt,name=wx_mini_app_open_id,json=wxMiniAppOpenId,proto3" json:"wx_mini_app_open_id,omitempty"` // 微信小程序openID（可选）
	ImageUrl        string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                            // 头像URL（可选）
	UserType        string                 `protobuf:"bytes,9,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                            // 用户类型（可选）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RegisterRequest) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

func (x *RegisterRequest) GetWxMiniAppOpenId() string {
	if x != nil {
		return x.WxMiniAppOpenId
	}
	return ""
}

func (x *RegisterRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RegisterRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	User          *UserInfo              `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 用户信息
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`     // 登录令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 手机号
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                          // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	User          *UserInfo              `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 用户信息
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`     // 登录令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 用户信息
type UserInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // 用户ID
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // 用户名
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                  // 邮箱
	Gender          int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                               // 性别
	PhoneNumber     string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                   // 手机号
	WxMiniAppOpenId string                 `protobuf:"bytes,6,opt,name=wx_mini_app_open_id,json=wxMiniAppOpenId,proto3" json:"wx_mini_app_open_id,omitempty"` // 微信小程序openID
	ChineseName     string                 `protobuf:"bytes,7,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`                   // 中文姓名
	Status          int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                                               // 状态
	CreateTime      string                 `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                      // 创建时间
	ImageUrl        string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                           // 头像URL
	RegisterSource  string                 `protobuf:"bytes,11,opt,name=register_source,json=registerSource,proto3" json:"register_source,omitempty"`         // 注册来源
	UserType        string                 `protobuf:"bytes,12,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                           // 用户类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserInfo) GetWxMiniAppOpenId() string {
	if x != nil {
		return x.WxMiniAppOpenId
	}
	return ""
}

func (x *UserInfo) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UserInfo) GetRegisterSource() string {
	if x != nil {
		return x.RegisterSource
	}
	return ""
}

func (x *UserInfo) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 管理员用户登录请求
type LoginAdminUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                    // 用户名（管理员账号）
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                    // 密码
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // 登录IP地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminUserRequest) Reset() {
	*x = LoginAdminUserRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminUserRequest) ProtoMessage() {}

func (x *LoginAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminUserRequest.ProtoReflect.Descriptor instead.
func (*LoginAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginAdminUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginAdminUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginAdminUserRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// 管理员用户登录响应
type LoginAdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AdminUser     *AdminUserInfo         `protobuf:"bytes,3,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"` // 管理员用户信息
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                          // 登录令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminUserResponse) Reset() {
	*x = LoginAdminUserResponse{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminUserResponse) ProtoMessage() {}

func (x *LoginAdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminUserResponse.ProtoReflect.Descriptor instead.
func (*LoginAdminUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginAdminUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginAdminUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginAdminUserResponse) GetAdminUser() *AdminUserInfo {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

func (x *LoginAdminUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 管理员用户信息
type AdminUserInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // 自增ID
	AdminId            string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`                                     // 管理员ID
	Username           string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                  // 用户名
	RealName           string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`                                  // 真实姓名
	Email              string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                                                        // 邮箱
	Role               string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`                                                          // 角色
	Status             int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                                     // 状态
	LastLoginTime      string                 `protobuf:"bytes,8,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`                 // 最后登录时间
	LastLoginIp        string                 `protobuf:"bytes,9,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`                       // 最后登录IP
	LoginFailCount     int32                  `protobuf:"varint,10,opt,name=login_fail_count,json=loginFailCount,proto3" json:"login_fail_count,omitempty"`            // 登录失败次数
	PasswordUpdateTime string                 `protobuf:"bytes,11,opt,name=password_update_time,json=passwordUpdateTime,proto3" json:"password_update_time,omitempty"` // 密码最后更新时间
	CreateTime         string                 `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                           // 创建时间
	UpdateTime         string                 `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                           // 最后更新时间
	Remark             string                 `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`                                                     // 备注
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AdminUserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *AdminUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AdminUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AdminUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminUserInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *AdminUserInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *AdminUserInfo) GetLoginFailCount() int32 {
	if x != nil {
		return x.LoginFailCount
	}
	return 0
}

func (x *AdminUserInfo) GetPasswordUpdateTime() string {
	if x != nil {
		return x.PasswordUpdateTime
	}
	return ""
}

func (x *AdminUserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *AdminUserInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *AdminUserInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x18trpc.elysia.backend.auth\"\xa6\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12!\n" +
	"\fchinese_name\x18\x06 \x01(\tR\vchineseName\x12,\n" +
	"\x13wx_mini_app_open_id\x18\a \x01(\tR\x0fwxMiniAppOpenId\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tuser_type\x18\t \x01(\tR\buserType\"\x8e\x01\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04user\x18\x03 \x01(\v2\".trpc.elysia.backend.auth.UserInfoR\x04user\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"M\n" +
	"\fLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8b\x01\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04user\x18\x03 \x01(\v2\".trpc.elysia.backend.auth.UserInfoR\x04user\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\xfe\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12,\n" +
	"\x13wx_mini_app_open_id\x18\x06 \x01(\tR\x0fwxMiniAppOpenId\x12!\n" +
	"\fchinese_name\x18\a \x01(\tR\vchineseName\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x12'\n" +
	"\x0fregister_source\x18\v \x01(\tR\x0eregisterSource\x12\x1b\n" +
	"\tuser_type\x18\f \x01(\tR\buserType\"n\n" +
	"\x15LoginAdminUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"\xa4\x01\n" +
	"\x16LoginAdminUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\n" +
	"admin_user\x18\x03 \x01(\v2'.trpc.elysia.backend.auth.AdminUserInfoR\tadminUser\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\xb7\x03\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12&\n" +
	"\x0flast_login_time\x18\b \x01(\tR\rlastLoginTime\x12\"\n" +
	"\rlast_login_ip\x18\t \x01(\tR\vlastLoginIp\x12(\n" +
	"\x10login_fail_count\x18\n" +
	" \x01(\x05R\x0eloginFailCount\x120\n" +
	"\x14password_update_time\x18\v \x01(\tR\x12passwordUpdateTime\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\r \x01(\tR\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\x0e \x01(\tR\x06remark2\xbf\x02\n" +
	"\vAuthService\x12a\n" +
	"\bRegister\x12).trpc.elysia.backend.auth.RegisterRequest\x1a*.trpc.elysia.backend.auth.RegisterResponse\x12X\n" +
	"\x05Login\x12&.trpc.elysia.backend.auth.LoginRequest\x1a'.trpc.elysia.backend.auth.LoginResponse\x12s\n" +
	"\x0eLoginAdminUser\x12/.trpc.elysia.backend.auth.LoginAdminUserRequest\x1a0.trpc.elysia.backend.auth.LoginAdminUserResponseB-Z+github.com/yzf120/elysia-backend/proto/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: trpc.elysia.backend.auth.RegisterRequest
	(*RegisterResponse)(nil),       // 1: trpc.elysia.backend.auth.RegisterResponse
	(*LoginRequest)(nil),           // 2: trpc.elysia.backend.auth.LoginRequest
	(*LoginResponse)(nil),          // 3: trpc.elysia.backend.auth.LoginResponse
	(*UserInfo)(nil),               // 4: trpc.elysia.backend.auth.UserInfo
	(*LoginAdminUserRequest)(nil),  // 5: trpc.elysia.backend.auth.LoginAdminUserRequest
	(*LoginAdminUserResponse)(nil), // 6: trpc.elysia.backend.auth.LoginAdminUserResponse
	(*AdminUserInfo)(nil),          // 7: trpc.elysia.backend.auth.AdminUserInfo
}
var file_auth_auth_proto_depIdxs = []int32{
	4, // 0: trpc.elysia.backend.auth.RegisterResponse.user:type_name -> trpc.elysia.backend.auth.UserInfo
	4, // 1: trpc.elysia.backend.auth.LoginResponse.user:type_name -> trpc.elysia.backend.auth.UserInfo
	7, // 2: trpc.elysia.backend.auth.LoginAdminUserResponse.admin_user:type_name -> trpc.elysia.backend.auth.AdminUserInfo
	0, // 3: trpc.elysia.backend.auth.AuthService.Register:input_type -> trpc.elysia.backend.auth.RegisterRequest
	2, // 4: trpc.elysia.backend.auth.AuthService.Login:input_type -> trpc.elysia.backend.auth.LoginRequest
	5, // 5: trpc.elysia.backend.auth.AuthService.LoginAdminUser:input_type -> trpc.elysia.backend.auth.LoginAdminUserRequest
	1, // 6: trpc.elysia.backend.auth.AuthService.Register:output_type -> trpc.elysia.backend.auth.RegisterResponse
	3, // 7: trpc.elysia.backend.auth.AuthService.Login:output_type -> trpc.elysia.backend.auth.LoginResponse
	6, // 8: trpc.elysia.backend.auth.AuthService.LoginAdminUser:output_type -> trpc.elysia.backend.auth.LoginAdminUserResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
