// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: auth/auth.proto

package auth

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AuthServiceService defines service.
type AuthServiceService interface {
	// Register 用户注册
	Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error)
	// Login 用户登录
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
	// LoginAdminUser 管理员用户登录
	LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest) (*LoginAdminUserResponse, error)
}

func AuthServiceService_Register_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RegisterRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthServiceService).Register(ctx, reqbody.(*RegisterRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthServiceService_Login_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthServiceService).Login(ctx, reqbody.(*LoginRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthServiceService_LoginAdminUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginAdminUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthServiceService).LoginAdminUser(ctx, reqbody.(*LoginAdminUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AuthServiceServer_ServiceDesc descriptor for server.RegisterService.
var AuthServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.auth.AuthService",
	HandlerType: ((*AuthServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.auth.AuthService/Register",
			Func: AuthServiceService_Register_Handler,
		},
		{
			Name: "/trpc.elysia.backend.auth.AuthService/Login",
			Func: AuthServiceService_Login_Handler,
		},
		{
			Name: "/trpc.elysia.backend.auth.AuthService/LoginAdminUser",
			Func: AuthServiceService_LoginAdminUser_Handler,
		},
	},
}

// RegisterAuthServiceService registers service.
func RegisterAuthServiceService(s server.Service, svr AuthServiceService) {
	if err := s.Register(&AuthServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AuthService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAuthService struct{}

// Register 用户注册
func (s *UnimplementedAuthService) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, errors.New("rpc Register of service AuthService is not implemented")
}

// Login 用户登录
func (s *UnimplementedAuthService) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, errors.New("rpc Login of service AuthService is not implemented")
}

// LoginAdminUser 管理员用户登录
func (s *UnimplementedAuthService) LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest) (*LoginAdminUserResponse, error) {
	return nil, errors.New("rpc LoginAdminUser of service AuthService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AuthServiceClientProxy defines service client proxy
type AuthServiceClientProxy interface {
	// Register 用户注册
	Register(ctx context.Context, req *RegisterRequest, opts ...client.Option) (rsp *RegisterResponse, err error)
	// Login 用户登录
	Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (rsp *LoginResponse, err error)
	// LoginAdminUser 管理员用户登录
	LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest, opts ...client.Option) (rsp *LoginAdminUserResponse, err error)
}

type AuthServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAuthServiceClientProxy = func(opts ...client.Option) AuthServiceClientProxy {
	return &AuthServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AuthServiceClientProxyImpl) Register(ctx context.Context, req *RegisterRequest, opts ...client.Option) (*RegisterResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.auth.AuthService/Register")
	msg.WithCalleeServiceName(AuthServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AuthService")
	msg.WithCalleeMethod("Register")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RegisterResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthServiceClientProxyImpl) Login(ctx context.Context, req *LoginRequest, opts ...client.Option) (*LoginResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.auth.AuthService/Login")
	msg.WithCalleeServiceName(AuthServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AuthService")
	msg.WithCalleeMethod("Login")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthServiceClientProxyImpl) LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest, opts ...client.Option) (*LoginAdminUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.auth.AuthService/LoginAdminUser")
	msg.WithCalleeServiceName(AuthServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AuthService")
	msg.WithCalleeMethod("LoginAdminUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginAdminUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
