// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: session/session.proto

package session

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// SessionServiceService defines service.
type SessionServiceService interface {
	CreateSession(ctx context.Context, req *CreateSessionRequest) (*CreateSessionResponse, error)

	GetSession(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error)

	UpdateSession(ctx context.Context, req *UpdateSessionRequest) (*UpdateSessionResponse, error)

	DeleteSession(ctx context.Context, req *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

func SessionServiceService_CreateSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateSessionRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SessionServiceService).CreateSession(ctx, reqbody.(*CreateSessionRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SessionServiceService_GetSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetSessionRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SessionServiceService).GetSession(ctx, reqbody.(*GetSessionRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SessionServiceService_UpdateSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateSessionRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SessionServiceService).UpdateSession(ctx, reqbody.(*UpdateSessionRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SessionServiceService_DeleteSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteSessionRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SessionServiceService).DeleteSession(ctx, reqbody.(*DeleteSessionRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// SessionServiceServer_ServiceDesc descriptor for server.RegisterService.
var SessionServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.session.SessionService",
	HandlerType: ((*SessionServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.session.SessionService/CreateSession",
			Func: SessionServiceService_CreateSession_Handler,
		},
		{
			Name: "/trpc.elysia.backend.session.SessionService/GetSession",
			Func: SessionServiceService_GetSession_Handler,
		},
		{
			Name: "/trpc.elysia.backend.session.SessionService/UpdateSession",
			Func: SessionServiceService_UpdateSession_Handler,
		},
		{
			Name: "/trpc.elysia.backend.session.SessionService/DeleteSession",
			Func: SessionServiceService_DeleteSession_Handler,
		},
	},
}

// RegisterSessionServiceService registers service.
func RegisterSessionServiceService(s server.Service, svr SessionServiceService) {
	if err := s.Register(&SessionServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("SessionService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedSessionService struct{}

func (s *UnimplementedSessionService) CreateSession(ctx context.Context, req *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, errors.New("rpc CreateSession of service SessionService is not implemented")
}
func (s *UnimplementedSessionService) GetSession(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, errors.New("rpc GetSession of service SessionService is not implemented")
}
func (s *UnimplementedSessionService) UpdateSession(ctx context.Context, req *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, errors.New("rpc UpdateSession of service SessionService is not implemented")
}
func (s *UnimplementedSessionService) DeleteSession(ctx context.Context, req *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, errors.New("rpc DeleteSession of service SessionService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// SessionServiceClientProxy defines service client proxy
type SessionServiceClientProxy interface {
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...client.Option) (rsp *CreateSessionResponse, err error)

	GetSession(ctx context.Context, req *GetSessionRequest, opts ...client.Option) (rsp *GetSessionResponse, err error)

	UpdateSession(ctx context.Context, req *UpdateSessionRequest, opts ...client.Option) (rsp *UpdateSessionResponse, err error)

	DeleteSession(ctx context.Context, req *DeleteSessionRequest, opts ...client.Option) (rsp *DeleteSessionResponse, err error)
}

type SessionServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewSessionServiceClientProxy = func(opts ...client.Option) SessionServiceClientProxy {
	return &SessionServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *SessionServiceClientProxyImpl) CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...client.Option) (*CreateSessionResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.session.SessionService/CreateSession")
	msg.WithCalleeServiceName(SessionServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SessionService")
	msg.WithCalleeMethod("CreateSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateSessionResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SessionServiceClientProxyImpl) GetSession(ctx context.Context, req *GetSessionRequest, opts ...client.Option) (*GetSessionResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.session.SessionService/GetSession")
	msg.WithCalleeServiceName(SessionServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SessionService")
	msg.WithCalleeMethod("GetSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetSessionResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SessionServiceClientProxyImpl) UpdateSession(ctx context.Context, req *UpdateSessionRequest, opts ...client.Option) (*UpdateSessionResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.session.SessionService/UpdateSession")
	msg.WithCalleeServiceName(SessionServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SessionService")
	msg.WithCalleeMethod("UpdateSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateSessionResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SessionServiceClientProxyImpl) DeleteSession(ctx context.Context, req *DeleteSessionRequest, opts ...client.Option) (*DeleteSessionResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.session.SessionService/DeleteSession")
	msg.WithCalleeServiceName(SessionServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SessionService")
	msg.WithCalleeMethod("DeleteSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteSessionResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
