// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: group_chat/group_chat.proto

package group_chat

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_group_chat_group_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_chat_group_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_chat_group_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_group_chat_group_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_chat_group_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_chat_group_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_group_chat_group_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_chat_group_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_chat_group_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_group_chat_group_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_chat_group_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_chat_group_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGroupResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_group_chat_group_chat_proto protoreflect.FileDescriptor

const file_group_chat_group_chat_proto_rawDesc = "" +
	"\n" +
	"\x1bgroup_chat/group_chat.proto\x12\x1etrpc.elysia.backend.group_chat\"J\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"f\n" +
	"\x13CreateGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"c\n" +
	"\x10GetGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\xfd\x01\n" +
	"\x10GroupChatService\x12x\n" +
	"\vCreateGroup\x122.trpc.elysia.backend.group_chat.CreateGroupRequest\x1a3.trpc.elysia.backend.group_chat.CreateGroupResponse\"\x00\x12o\n" +
	"\bGetGroup\x12/.trpc.elysia.backend.group_chat.GetGroupRequest\x1a0.trpc.elysia.backend.group_chat.GetGroupResponse\"\x00B3Z1github.com/yzf120/elysia-backend/proto/group_chatb\x06proto3"

var (
	file_group_chat_group_chat_proto_rawDescOnce sync.Once
	file_group_chat_group_chat_proto_rawDescData []byte
)

func file_group_chat_group_chat_proto_rawDescGZIP() []byte {
	file_group_chat_group_chat_proto_rawDescOnce.Do(func() {
		file_group_chat_group_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_chat_group_chat_proto_rawDesc), len(file_group_chat_group_chat_proto_rawDesc)))
	})
	return file_group_chat_group_chat_proto_rawDescData
}

var file_group_chat_group_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_group_chat_group_chat_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),  // 0: trpc.elysia.backend.group_chat.CreateGroupRequest
	(*CreateGroupResponse)(nil), // 1: trpc.elysia.backend.group_chat.CreateGroupResponse
	(*GetGroupRequest)(nil),     // 2: trpc.elysia.backend.group_chat.GetGroupRequest
	(*GetGroupResponse)(nil),    // 3: trpc.elysia.backend.group_chat.GetGroupResponse
}
var file_group_chat_group_chat_proto_depIdxs = []int32{
	0, // 0: trpc.elysia.backend.group_chat.GroupChatService.CreateGroup:input_type -> trpc.elysia.backend.group_chat.CreateGroupRequest
	2, // 1: trpc.elysia.backend.group_chat.GroupChatService.GetGroup:input_type -> trpc.elysia.backend.group_chat.GetGroupRequest
	1, // 2: trpc.elysia.backend.group_chat.GroupChatService.CreateGroup:output_type -> trpc.elysia.backend.group_chat.CreateGroupResponse
	3, // 3: trpc.elysia.backend.group_chat.GroupChatService.GetGroup:output_type -> trpc.elysia.backend.group_chat.GetGroupResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_group_chat_group_chat_proto_init() }
func file_group_chat_group_chat_proto_init() {
	if File_group_chat_group_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_chat_group_chat_proto_rawDesc), len(file_group_chat_group_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_chat_group_chat_proto_goTypes,
		DependencyIndexes: file_group_chat_group_chat_proto_depIdxs,
		MessageInfos:      file_group_chat_group_chat_proto_msgTypes,
	}.Build()
	File_group_chat_group_chat_proto = out.File
	file_group_chat_group_chat_proto_goTypes = nil
	file_group_chat_group_chat_proto_depIdxs = nil
}
