// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: group_chat/group_chat.proto

package group_chat

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GroupChatServiceService defines service.
type GroupChatServiceService interface {
	CreateGroup(ctx context.Context, req *CreateGroupRequest) (*CreateGroupResponse, error)

	GetGroup(ctx context.Context, req *GetGroupRequest) (*GetGroupResponse, error)
}

func GroupChatServiceService_CreateGroup_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateGroupRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GroupChatServiceService).CreateGroup(ctx, reqbody.(*CreateGroupRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func GroupChatServiceService_GetGroup_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetGroupRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GroupChatServiceService).GetGroup(ctx, reqbody.(*GetGroupRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// GroupChatServiceServer_ServiceDesc descriptor for server.RegisterService.
var GroupChatServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.group_chat.GroupChatService",
	HandlerType: ((*GroupChatServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.group_chat.GroupChatService/CreateGroup",
			Func: GroupChatServiceService_CreateGroup_Handler,
		},
		{
			Name: "/trpc.elysia.backend.group_chat.GroupChatService/GetGroup",
			Func: GroupChatServiceService_GetGroup_Handler,
		},
	},
}

// RegisterGroupChatServiceService registers service.
func RegisterGroupChatServiceService(s server.Service, svr GroupChatServiceService) {
	if err := s.Register(&GroupChatServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("GroupChatService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGroupChatService struct{}

func (s *UnimplementedGroupChatService) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, errors.New("rpc CreateGroup of service GroupChatService is not implemented")
}
func (s *UnimplementedGroupChatService) GetGroup(ctx context.Context, req *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, errors.New("rpc GetGroup of service GroupChatService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GroupChatServiceClientProxy defines service client proxy
type GroupChatServiceClientProxy interface {
	CreateGroup(ctx context.Context, req *CreateGroupRequest, opts ...client.Option) (rsp *CreateGroupResponse, err error)

	GetGroup(ctx context.Context, req *GetGroupRequest, opts ...client.Option) (rsp *GetGroupResponse, err error)
}

type GroupChatServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGroupChatServiceClientProxy = func(opts ...client.Option) GroupChatServiceClientProxy {
	return &GroupChatServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GroupChatServiceClientProxyImpl) CreateGroup(ctx context.Context, req *CreateGroupRequest, opts ...client.Option) (*CreateGroupResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.group_chat.GroupChatService/CreateGroup")
	msg.WithCalleeServiceName(GroupChatServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("GroupChatService")
	msg.WithCalleeMethod("CreateGroup")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateGroupResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *GroupChatServiceClientProxyImpl) GetGroup(ctx context.Context, req *GetGroupRequest, opts ...client.Option) (*GetGroupResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.group_chat.GroupChatService/GetGroup")
	msg.WithCalleeServiceName(GroupChatServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("GroupChatService")
	msg.WithCalleeMethod("GetGroup")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetGroupResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
