// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: admin/admin.proto

package admin

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建管理员用户请求
type CreateAdminUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                 // 用户名（登录账号）
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                 // 密码
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // 真实姓名
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                       // 邮箱
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                         // 角色：admin, super_admin
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`                     // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminUserRequest) Reset() {
	*x = CreateAdminUserRequest{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminUserRequest) ProtoMessage() {}

func (x *CreateAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminUserRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAdminUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAdminUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminUserRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CreateAdminUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateAdminUserRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建管理员用户响应
type CreateAdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AdminUser     *AdminUserInfo         `protobuf:"bytes,3,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"` // 管理员用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminUserResponse) Reset() {
	*x = CreateAdminUserResponse{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminUserResponse) ProtoMessage() {}

func (x *CreateAdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminUserResponse.ProtoReflect.Descriptor instead.
func (*CreateAdminUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdminUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAdminUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAdminUserResponse) GetAdminUser() *AdminUserInfo {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

// 管理员用户登录请求
type LoginAdminUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                    // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                    // 密码
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // 登录IP地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminUserRequest) Reset() {
	*x = LoginAdminUserRequest{}
	mi := &file_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminUserRequest) ProtoMessage() {}

func (x *LoginAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminUserRequest.ProtoReflect.Descriptor instead.
func (*LoginAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginAdminUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginAdminUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginAdminUserRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// 管理员用户登录响应
type LoginAdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AdminUser     *AdminUserInfo         `protobuf:"bytes,3,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"` // 管理员用户信息
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                          // 登录令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminUserResponse) Reset() {
	*x = LoginAdminUserResponse{}
	mi := &file_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminUserResponse) ProtoMessage() {}

func (x *LoginAdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminUserResponse.ProtoReflect.Descriptor instead.
func (*LoginAdminUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *LoginAdminUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginAdminUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginAdminUserResponse) GetAdminUser() *AdminUserInfo {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

func (x *LoginAdminUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 更新管理员用户密码请求
type UpdateAdminUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`             // 管理员ID
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"` // 旧密码
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"` // 新密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminUserPasswordRequest) Reset() {
	*x = UpdateAdminUserPasswordRequest{}
	mi := &file_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminUserPasswordRequest) ProtoMessage() {}

func (x *UpdateAdminUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAdminUserPasswordRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *UpdateAdminUserPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateAdminUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 更新管理员用户密码响应
type UpdateAdminUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminUserPasswordResponse) Reset() {
	*x = UpdateAdminUserPasswordResponse{}
	mi := &file_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminUserPasswordResponse) ProtoMessage() {}

func (x *UpdateAdminUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdminUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAdminUserPasswordResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateAdminUserPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询管理员用户请求
type GetAdminUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"` // 管理员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserRequest) Reset() {
	*x = GetAdminUserRequest{}
	mi := &file_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserRequest) ProtoMessage() {}

func (x *GetAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserRequest.ProtoReflect.Descriptor instead.
func (*GetAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetAdminUserRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

// 查询管理员用户响应
type GetAdminUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 响应消息
	AdminUser     *AdminUserInfo         `protobuf:"bytes,3,opt,name=admin_user,json=adminUser,proto3" json:"admin_user,omitempty"` // 管理员用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserResponse) Reset() {
	*x = GetAdminUserResponse{}
	mi := &file_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserResponse) ProtoMessage() {}

func (x *GetAdminUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserResponse.ProtoReflect.Descriptor instead.
func (*GetAdminUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetAdminUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAdminUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAdminUserResponse) GetAdminUser() *AdminUserInfo {
	if x != nil {
		return x.AdminUser
	}
	return nil
}

// 查询管理员用户列表请求
type ListAdminUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                          // 角色过滤（可选）
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                      // 状态过滤（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersRequest) Reset() {
	*x = ListAdminUsersRequest{}
	mi := &file_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersRequest) ProtoMessage() {}

func (x *ListAdminUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersRequest.ProtoReflect.Descriptor instead.
func (*ListAdminUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListAdminUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListAdminUsersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 查询管理员用户列表响应
type ListAdminUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                              // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	AdminUsers    []*AdminUserInfo       `protobuf:"bytes,3,rep,name=admin_users,json=adminUsers,proto3" json:"admin_users,omitempty"` // 管理员用户列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`                            // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResponse) Reset() {
	*x = ListAdminUsersResponse{}
	mi := &file_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResponse) ProtoMessage() {}

func (x *ListAdminUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdminUsersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListAdminUsersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAdminUsersResponse) GetAdminUsers() []*AdminUserInfo {
	if x != nil {
		return x.AdminUsers
	}
	return nil
}

func (x *ListAdminUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 更新管理员用户状态请求
type UpdateAdminUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"` // 管理员ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                 // 状态：0-禁用，1-启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminUserStatusRequest) Reset() {
	*x = UpdateAdminUserStatusRequest{}
	mi := &file_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminUserStatusRequest) ProtoMessage() {}

func (x *UpdateAdminUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAdminUserStatusRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *UpdateAdminUserStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 更新管理员用户状态响应
type UpdateAdminUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminUserStatusResponse) Reset() {
	*x = UpdateAdminUserStatusResponse{}
	mi := &file_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminUserStatusResponse) ProtoMessage() {}

func (x *UpdateAdminUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminUserStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdminUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAdminUserStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateAdminUserStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 管理员用户信息
type AdminUserInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // 自增ID
	AdminId            string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`                                     // 管理员ID
	Username           string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                  // 用户名
	RealName           string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`                                  // 真实姓名
	Email              string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                                                        // 邮箱
	Role               string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`                                                          // 角色
	Status             int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                                     // 状态
	LastLoginTime      string                 `protobuf:"bytes,8,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`                 // 最后登录时间
	LastLoginIp        string                 `protobuf:"bytes,9,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`                       // 最后登录IP
	LoginFailCount     int32                  `protobuf:"varint,10,opt,name=login_fail_count,json=loginFailCount,proto3" json:"login_fail_count,omitempty"`            // 登录失败次数
	PasswordUpdateTime string                 `protobuf:"bytes,11,opt,name=password_update_time,json=passwordUpdateTime,proto3" json:"password_update_time,omitempty"` // 密码最后更新时间
	CreateTime         string                 `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                           // 创建时间
	UpdateTime         string                 `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                           // 最后更新时间
	Remark             string                 `protobuf:"bytes,14,opt,name=remark,proto3" json:"remark,omitempty"`                                                     // 备注
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *AdminUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AdminUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AdminUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminUserInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *AdminUserInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *AdminUserInfo) GetLoginFailCount() int32 {
	if x != nil {
		return x.LoginFailCount
	}
	return 0
}

func (x *AdminUserInfo) GetPasswordUpdateTime() string {
	if x != nil {
		return x.PasswordUpdateTime
	}
	return ""
}

func (x *AdminUserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *AdminUserInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *AdminUserInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\x19trpc.elysia.backend.admin\"\xaf\x01\n" +
	"\x16CreateAdminUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"\x90\x01\n" +
	"\x17CreateAdminUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\n" +
	"admin_user\x18\x03 \x01(\v2(.trpc.elysia.backend.admin.AdminUserInfoR\tadminUser\"n\n" +
	"\x15LoginAdminUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"\xa5\x01\n" +
	"\x16LoginAdminUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\n" +
	"admin_user\x18\x03 \x01(\v2(.trpc.elysia.backend.admin.AdminUserInfoR\tadminUser\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\x81\x01\n" +
	"\x1eUpdateAdminUserPasswordRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"O\n" +
	"\x1fUpdateAdminUserPasswordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x13GetAdminUserRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\"\x8d\x01\n" +
	"\x14GetAdminUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\n" +
	"admin_user\x18\x03 \x01(\v2(.trpc.elysia.backend.admin.AdminUserInfoR\tadminUser\"t\n" +
	"\x15ListAdminUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xa7\x01\n" +
	"\x16ListAdminUsersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\vadmin_users\x18\x03 \x03(\v2(.trpc.elysia.backend.admin.AdminUserInfoR\n" +
	"adminUsers\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"Q\n" +
	"\x1cUpdateAdminUserStatusRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"M\n" +
	"\x1dUpdateAdminUserStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x03\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12&\n" +
	"\x0flast_login_time\x18\b \x01(\tR\rlastLoginTime\x12\"\n" +
	"\rlast_login_ip\x18\t \x01(\tR\vlastLoginIp\x12(\n" +
	"\x10login_fail_count\x18\n" +
	" \x01(\x05R\x0eloginFailCount\x120\n" +
	"\x14password_update_time\x18\v \x01(\tR\x12passwordUpdateTime\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\r \x01(\tR\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\x0e \x01(\tR\x06remark2\x8b\x06\n" +
	"\x10AdminUserService\x12x\n" +
	"\x0fCreateAdminUser\x121.trpc.elysia.backend.admin.CreateAdminUserRequest\x1a2.trpc.elysia.backend.admin.CreateAdminUserResponse\x12u\n" +
	"\x0eLoginAdminUser\x120.trpc.elysia.backend.admin.LoginAdminUserRequest\x1a1.trpc.elysia.backend.admin.LoginAdminUserResponse\x12\x90\x01\n" +
	"\x17UpdateAdminUserPassword\x129.trpc.elysia.backend.admin.UpdateAdminUserPasswordRequest\x1a:.trpc.elysia.backend.admin.UpdateAdminUserPasswordResponse\x12o\n" +
	"\fGetAdminUser\x12..trpc.elysia.backend.admin.GetAdminUserRequest\x1a/.trpc.elysia.backend.admin.GetAdminUserResponse\x12u\n" +
	"\x0eListAdminUsers\x120.trpc.elysia.backend.admin.ListAdminUsersRequest\x1a1.trpc.elysia.backend.admin.ListAdminUsersResponse\x12\x8a\x01\n" +
	"\x15UpdateAdminUserStatus\x127.trpc.elysia.backend.admin.UpdateAdminUserStatusRequest\x1a8.trpc.elysia.backend.admin.UpdateAdminUserStatusResponseB.Z,github.com/yzf120/elysia-backend/proto/adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_admin_admin_proto_goTypes = []any{
	(*CreateAdminUserRequest)(nil),          // 0: trpc.elysia.backend.admin.CreateAdminUserRequest
	(*CreateAdminUserResponse)(nil),         // 1: trpc.elysia.backend.admin.CreateAdminUserResponse
	(*LoginAdminUserRequest)(nil),           // 2: trpc.elysia.backend.admin.LoginAdminUserRequest
	(*LoginAdminUserResponse)(nil),          // 3: trpc.elysia.backend.admin.LoginAdminUserResponse
	(*UpdateAdminUserPasswordRequest)(nil),  // 4: trpc.elysia.backend.admin.UpdateAdminUserPasswordRequest
	(*UpdateAdminUserPasswordResponse)(nil), // 5: trpc.elysia.backend.admin.UpdateAdminUserPasswordResponse
	(*GetAdminUserRequest)(nil),             // 6: trpc.elysia.backend.admin.GetAdminUserRequest
	(*GetAdminUserResponse)(nil),            // 7: trpc.elysia.backend.admin.GetAdminUserResponse
	(*ListAdminUsersRequest)(nil),           // 8: trpc.elysia.backend.admin.ListAdminUsersRequest
	(*ListAdminUsersResponse)(nil),          // 9: trpc.elysia.backend.admin.ListAdminUsersResponse
	(*UpdateAdminUserStatusRequest)(nil),    // 10: trpc.elysia.backend.admin.UpdateAdminUserStatusRequest
	(*UpdateAdminUserStatusResponse)(nil),   // 11: trpc.elysia.backend.admin.UpdateAdminUserStatusResponse
	(*AdminUserInfo)(nil),                   // 12: trpc.elysia.backend.admin.AdminUserInfo
}
var file_admin_admin_proto_depIdxs = []int32{
	12, // 0: trpc.elysia.backend.admin.CreateAdminUserResponse.admin_user:type_name -> trpc.elysia.backend.admin.AdminUserInfo
	12, // 1: trpc.elysia.backend.admin.LoginAdminUserResponse.admin_user:type_name -> trpc.elysia.backend.admin.AdminUserInfo
	12, // 2: trpc.elysia.backend.admin.GetAdminUserResponse.admin_user:type_name -> trpc.elysia.backend.admin.AdminUserInfo
	12, // 3: trpc.elysia.backend.admin.ListAdminUsersResponse.admin_users:type_name -> trpc.elysia.backend.admin.AdminUserInfo
	0,  // 4: trpc.elysia.backend.admin.AdminUserService.CreateAdminUser:input_type -> trpc.elysia.backend.admin.CreateAdminUserRequest
	2,  // 5: trpc.elysia.backend.admin.AdminUserService.LoginAdminUser:input_type -> trpc.elysia.backend.admin.LoginAdminUserRequest
	4,  // 6: trpc.elysia.backend.admin.AdminUserService.UpdateAdminUserPassword:input_type -> trpc.elysia.backend.admin.UpdateAdminUserPasswordRequest
	6,  // 7: trpc.elysia.backend.admin.AdminUserService.GetAdminUser:input_type -> trpc.elysia.backend.admin.GetAdminUserRequest
	8,  // 8: trpc.elysia.backend.admin.AdminUserService.ListAdminUsers:input_type -> trpc.elysia.backend.admin.ListAdminUsersRequest
	10, // 9: trpc.elysia.backend.admin.AdminUserService.UpdateAdminUserStatus:input_type -> trpc.elysia.backend.admin.UpdateAdminUserStatusRequest
	1,  // 10: trpc.elysia.backend.admin.AdminUserService.CreateAdminUser:output_type -> trpc.elysia.backend.admin.CreateAdminUserResponse
	3,  // 11: trpc.elysia.backend.admin.AdminUserService.LoginAdminUser:output_type -> trpc.elysia.backend.admin.LoginAdminUserResponse
	5,  // 12: trpc.elysia.backend.admin.AdminUserService.UpdateAdminUserPassword:output_type -> trpc.elysia.backend.admin.UpdateAdminUserPasswordResponse
	7,  // 13: trpc.elysia.backend.admin.AdminUserService.GetAdminUser:output_type -> trpc.elysia.backend.admin.GetAdminUserResponse
	9,  // 14: trpc.elysia.backend.admin.AdminUserService.ListAdminUsers:output_type -> trpc.elysia.backend.admin.ListAdminUsersResponse
	11, // 15: trpc.elysia.backend.admin.AdminUserService.UpdateAdminUserStatus:output_type -> trpc.elysia.backend.admin.UpdateAdminUserStatusResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
