// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: admin/admin.proto

package admin

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AdminUserServiceService defines service.
type AdminUserServiceService interface {
	// CreateAdminUser 创建管理员用户
	CreateAdminUser(ctx context.Context, req *CreateAdminUserRequest) (*CreateAdminUserResponse, error)
	// LoginAdminUser 管理员用户登录
	LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest) (*LoginAdminUserResponse, error)
	// UpdateAdminUserPassword 更新管理员用户密码
	UpdateAdminUserPassword(ctx context.Context, req *UpdateAdminUserPasswordRequest) (*UpdateAdminUserPasswordResponse, error)
	// GetAdminUser 查询管理员用户信息
	GetAdminUser(ctx context.Context, req *GetAdminUserRequest) (*GetAdminUserResponse, error)
	// ListAdminUsers 查询管理员用户列表
	ListAdminUsers(ctx context.Context, req *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	// UpdateAdminUserStatus 更新管理员用户状态
	UpdateAdminUserStatus(ctx context.Context, req *UpdateAdminUserStatusRequest) (*UpdateAdminUserStatusResponse, error)
}

func AdminUserServiceService_CreateAdminUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateAdminUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).CreateAdminUser(ctx, reqbody.(*CreateAdminUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminUserServiceService_LoginAdminUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginAdminUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).LoginAdminUser(ctx, reqbody.(*LoginAdminUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminUserServiceService_UpdateAdminUserPassword_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateAdminUserPasswordRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).UpdateAdminUserPassword(ctx, reqbody.(*UpdateAdminUserPasswordRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminUserServiceService_GetAdminUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetAdminUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).GetAdminUser(ctx, reqbody.(*GetAdminUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminUserServiceService_ListAdminUsers_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListAdminUsersRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).ListAdminUsers(ctx, reqbody.(*ListAdminUsersRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AdminUserServiceService_UpdateAdminUserStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateAdminUserStatusRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AdminUserServiceService).UpdateAdminUserStatus(ctx, reqbody.(*UpdateAdminUserStatusRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AdminUserServiceServer_ServiceDesc descriptor for server.RegisterService.
var AdminUserServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.admin.AdminUserService",
	HandlerType: ((*AdminUserServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/CreateAdminUser",
			Func: AdminUserServiceService_CreateAdminUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/LoginAdminUser",
			Func: AdminUserServiceService_LoginAdminUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/UpdateAdminUserPassword",
			Func: AdminUserServiceService_UpdateAdminUserPassword_Handler,
		},
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/GetAdminUser",
			Func: AdminUserServiceService_GetAdminUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/ListAdminUsers",
			Func: AdminUserServiceService_ListAdminUsers_Handler,
		},
		{
			Name: "/trpc.elysia.backend.admin.AdminUserService/UpdateAdminUserStatus",
			Func: AdminUserServiceService_UpdateAdminUserStatus_Handler,
		},
	},
}

// RegisterAdminUserServiceService registers service.
func RegisterAdminUserServiceService(s server.Service, svr AdminUserServiceService) {
	if err := s.Register(&AdminUserServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AdminUserService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAdminUserService struct{}

// CreateAdminUser 创建管理员用户
func (s *UnimplementedAdminUserService) CreateAdminUser(ctx context.Context, req *CreateAdminUserRequest) (*CreateAdminUserResponse, error) {
	return nil, errors.New("rpc CreateAdminUser of service AdminUserService is not implemented")
}

// LoginAdminUser 管理员用户登录
func (s *UnimplementedAdminUserService) LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest) (*LoginAdminUserResponse, error) {
	return nil, errors.New("rpc LoginAdminUser of service AdminUserService is not implemented")
}

// UpdateAdminUserPassword 更新管理员用户密码
func (s *UnimplementedAdminUserService) UpdateAdminUserPassword(ctx context.Context, req *UpdateAdminUserPasswordRequest) (*UpdateAdminUserPasswordResponse, error) {
	return nil, errors.New("rpc UpdateAdminUserPassword of service AdminUserService is not implemented")
}

// GetAdminUser 查询管理员用户信息
func (s *UnimplementedAdminUserService) GetAdminUser(ctx context.Context, req *GetAdminUserRequest) (*GetAdminUserResponse, error) {
	return nil, errors.New("rpc GetAdminUser of service AdminUserService is not implemented")
}

// ListAdminUsers 查询管理员用户列表
func (s *UnimplementedAdminUserService) ListAdminUsers(ctx context.Context, req *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, errors.New("rpc ListAdminUsers of service AdminUserService is not implemented")
}

// UpdateAdminUserStatus 更新管理员用户状态
func (s *UnimplementedAdminUserService) UpdateAdminUserStatus(ctx context.Context, req *UpdateAdminUserStatusRequest) (*UpdateAdminUserStatusResponse, error) {
	return nil, errors.New("rpc UpdateAdminUserStatus of service AdminUserService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AdminUserServiceClientProxy defines service client proxy
type AdminUserServiceClientProxy interface {
	// CreateAdminUser 创建管理员用户
	CreateAdminUser(ctx context.Context, req *CreateAdminUserRequest, opts ...client.Option) (rsp *CreateAdminUserResponse, err error)
	// LoginAdminUser 管理员用户登录
	LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest, opts ...client.Option) (rsp *LoginAdminUserResponse, err error)
	// UpdateAdminUserPassword 更新管理员用户密码
	UpdateAdminUserPassword(ctx context.Context, req *UpdateAdminUserPasswordRequest, opts ...client.Option) (rsp *UpdateAdminUserPasswordResponse, err error)
	// GetAdminUser 查询管理员用户信息
	GetAdminUser(ctx context.Context, req *GetAdminUserRequest, opts ...client.Option) (rsp *GetAdminUserResponse, err error)
	// ListAdminUsers 查询管理员用户列表
	ListAdminUsers(ctx context.Context, req *ListAdminUsersRequest, opts ...client.Option) (rsp *ListAdminUsersResponse, err error)
	// UpdateAdminUserStatus 更新管理员用户状态
	UpdateAdminUserStatus(ctx context.Context, req *UpdateAdminUserStatusRequest, opts ...client.Option) (rsp *UpdateAdminUserStatusResponse, err error)
}

type AdminUserServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAdminUserServiceClientProxy = func(opts ...client.Option) AdminUserServiceClientProxy {
	return &AdminUserServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AdminUserServiceClientProxyImpl) CreateAdminUser(ctx context.Context, req *CreateAdminUserRequest, opts ...client.Option) (*CreateAdminUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/CreateAdminUser")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("CreateAdminUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateAdminUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminUserServiceClientProxyImpl) LoginAdminUser(ctx context.Context, req *LoginAdminUserRequest, opts ...client.Option) (*LoginAdminUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/LoginAdminUser")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("LoginAdminUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginAdminUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminUserServiceClientProxyImpl) UpdateAdminUserPassword(ctx context.Context, req *UpdateAdminUserPasswordRequest, opts ...client.Option) (*UpdateAdminUserPasswordResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/UpdateAdminUserPassword")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("UpdateAdminUserPassword")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateAdminUserPasswordResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminUserServiceClientProxyImpl) GetAdminUser(ctx context.Context, req *GetAdminUserRequest, opts ...client.Option) (*GetAdminUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/GetAdminUser")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("GetAdminUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetAdminUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminUserServiceClientProxyImpl) ListAdminUsers(ctx context.Context, req *ListAdminUsersRequest, opts ...client.Option) (*ListAdminUsersResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/ListAdminUsers")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("ListAdminUsers")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListAdminUsersResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AdminUserServiceClientProxyImpl) UpdateAdminUserStatus(ctx context.Context, req *UpdateAdminUserStatusRequest, opts ...client.Option) (*UpdateAdminUserStatusResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.admin.AdminUserService/UpdateAdminUserStatus")
	msg.WithCalleeServiceName(AdminUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AdminUserService")
	msg.WithCalleeMethod("UpdateAdminUserStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateAdminUserStatusResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
