// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: user_agent/user_agent.proto

package user_agent

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// UserAgentServiceService defines service.
type UserAgentServiceService interface {
	AssignAgent(ctx context.Context, req *AssignAgentRequest) (*AssignAgentResponse, error)

	GetUserAgents(ctx context.Context, req *GetUserAgentsRequest) (*GetUserAgentsResponse, error)

	RemoveAgent(ctx context.Context, req *RemoveAgentRequest) (*RemoveAgentResponse, error)

	UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigRequest) (*UpdateAgentConfigResponse, error)
}

func UserAgentServiceService_AssignAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AssignAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserAgentServiceService).AssignAgent(ctx, reqbody.(*AssignAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserAgentServiceService_GetUserAgents_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserAgentsRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserAgentServiceService).GetUserAgents(ctx, reqbody.(*GetUserAgentsRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserAgentServiceService_RemoveAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RemoveAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserAgentServiceService).RemoveAgent(ctx, reqbody.(*RemoveAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserAgentServiceService_UpdateAgentConfig_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateAgentConfigRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserAgentServiceService).UpdateAgentConfig(ctx, reqbody.(*UpdateAgentConfigRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// UserAgentServiceServer_ServiceDesc descriptor for server.RegisterService.
var UserAgentServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.user_agent.UserAgentService",
	HandlerType: ((*UserAgentServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.user_agent.UserAgentService/AssignAgent",
			Func: UserAgentServiceService_AssignAgent_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user_agent.UserAgentService/GetUserAgents",
			Func: UserAgentServiceService_GetUserAgents_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user_agent.UserAgentService/RemoveAgent",
			Func: UserAgentServiceService_RemoveAgent_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user_agent.UserAgentService/UpdateAgentConfig",
			Func: UserAgentServiceService_UpdateAgentConfig_Handler,
		},
	},
}

// RegisterUserAgentServiceService registers service.
func RegisterUserAgentServiceService(s server.Service, svr UserAgentServiceService) {
	if err := s.Register(&UserAgentServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("UserAgentService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedUserAgentService struct{}

func (s *UnimplementedUserAgentService) AssignAgent(ctx context.Context, req *AssignAgentRequest) (*AssignAgentResponse, error) {
	return nil, errors.New("rpc AssignAgent of service UserAgentService is not implemented")
}
func (s *UnimplementedUserAgentService) GetUserAgents(ctx context.Context, req *GetUserAgentsRequest) (*GetUserAgentsResponse, error) {
	return nil, errors.New("rpc GetUserAgents of service UserAgentService is not implemented")
}
func (s *UnimplementedUserAgentService) RemoveAgent(ctx context.Context, req *RemoveAgentRequest) (*RemoveAgentResponse, error) {
	return nil, errors.New("rpc RemoveAgent of service UserAgentService is not implemented")
}
func (s *UnimplementedUserAgentService) UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigRequest) (*UpdateAgentConfigResponse, error) {
	return nil, errors.New("rpc UpdateAgentConfig of service UserAgentService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// UserAgentServiceClientProxy defines service client proxy
type UserAgentServiceClientProxy interface {
	AssignAgent(ctx context.Context, req *AssignAgentRequest, opts ...client.Option) (rsp *AssignAgentResponse, err error)

	GetUserAgents(ctx context.Context, req *GetUserAgentsRequest, opts ...client.Option) (rsp *GetUserAgentsResponse, err error)

	RemoveAgent(ctx context.Context, req *RemoveAgentRequest, opts ...client.Option) (rsp *RemoveAgentResponse, err error)

	UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigRequest, opts ...client.Option) (rsp *UpdateAgentConfigResponse, err error)
}

type UserAgentServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewUserAgentServiceClientProxy = func(opts ...client.Option) UserAgentServiceClientProxy {
	return &UserAgentServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *UserAgentServiceClientProxyImpl) AssignAgent(ctx context.Context, req *AssignAgentRequest, opts ...client.Option) (*AssignAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user_agent.UserAgentService/AssignAgent")
	msg.WithCalleeServiceName(UserAgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserAgentService")
	msg.WithCalleeMethod("AssignAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AssignAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserAgentServiceClientProxyImpl) GetUserAgents(ctx context.Context, req *GetUserAgentsRequest, opts ...client.Option) (*GetUserAgentsResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user_agent.UserAgentService/GetUserAgents")
	msg.WithCalleeServiceName(UserAgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserAgentService")
	msg.WithCalleeMethod("GetUserAgents")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserAgentsResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserAgentServiceClientProxyImpl) RemoveAgent(ctx context.Context, req *RemoveAgentRequest, opts ...client.Option) (*RemoveAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user_agent.UserAgentService/RemoveAgent")
	msg.WithCalleeServiceName(UserAgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserAgentService")
	msg.WithCalleeMethod("RemoveAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RemoveAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserAgentServiceClientProxyImpl) UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigRequest, opts ...client.Option) (*UpdateAgentConfigResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user_agent.UserAgentService/UpdateAgentConfig")
	msg.WithCalleeServiceName(UserAgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserAgentService")
	msg.WithCalleeMethod("UpdateAgentConfig")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateAgentConfigResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
