// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user_agent/user_agent.proto

package user_agent

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // 用户特定的代理配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentRequest) Reset() {
	*x = AssignAgentRequest{}
	mi := &file_user_agent_user_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentRequest) ProtoMessage() {}

func (x *AssignAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentRequest.ProtoReflect.Descriptor instead.
func (*AssignAgentRequest) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AssignAgentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AssignAgentRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type AssignAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgentId   string                 `protobuf:"bytes,1,opt,name=user_agent_id,json=userAgentId,proto3" json:"user_agent_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	AssignedAt    string                 `protobuf:"bytes,5,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAgentResponse) Reset() {
	*x = AssignAgentResponse{}
	mi := &file_user_agent_user_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentResponse) ProtoMessage() {}

func (x *AssignAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentResponse.ProtoReflect.Descriptor instead.
func (*AssignAgentResponse) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AssignAgentResponse) GetUserAgentId() string {
	if x != nil {
		return x.UserAgentId
	}
	return ""
}

func (x *AssignAgentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AssignAgentResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *AssignAgentResponse) GetAssignedAt() string {
	if x != nil {
		return x.AssignedAt
	}
	return ""
}

type GetUserAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAgentsRequest) Reset() {
	*x = GetUserAgentsRequest{}
	mi := &file_user_agent_user_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAgentsRequest) ProtoMessage() {}

func (x *GetUserAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAgentsRequest) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserAgentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgents    []*UserAgentInfo       `protobuf:"bytes,1,rep,name=user_agents,json=userAgents,proto3" json:"user_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAgentsResponse) Reset() {
	*x = GetUserAgentsResponse{}
	mi := &file_user_agent_user_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAgentsResponse) ProtoMessage() {}

func (x *GetUserAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAgentsResponse) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserAgentsResponse) GetUserAgents() []*UserAgentInfo {
	if x != nil {
		return x.UserAgents
	}
	return nil
}

type UserAgentInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserAgentId      string                 `protobuf:"bytes,1,opt,name=user_agent_id,json=userAgentId,proto3" json:"user_agent_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId          string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName        string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentDescription string                 `protobuf:"bytes,5,opt,name=agent_description,json=agentDescription,proto3" json:"agent_description,omitempty"`
	Config           string                 `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	AssignedAt       string                 `protobuf:"bytes,7,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserAgentInfo) Reset() {
	*x = UserAgentInfo{}
	mi := &file_user_agent_user_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgentInfo) ProtoMessage() {}

func (x *UserAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgentInfo.ProtoReflect.Descriptor instead.
func (*UserAgentInfo) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UserAgentInfo) GetUserAgentId() string {
	if x != nil {
		return x.UserAgentId
	}
	return ""
}

func (x *UserAgentInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UserAgentInfo) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *UserAgentInfo) GetAgentDescription() string {
	if x != nil {
		return x.AgentDescription
	}
	return ""
}

func (x *UserAgentInfo) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UserAgentInfo) GetAssignedAt() string {
	if x != nil {
		return x.AssignedAt
	}
	return ""
}

type RemoveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgentId   string                 `protobuf:"bytes,1,opt,name=user_agent_id,json=userAgentId,proto3" json:"user_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentRequest) Reset() {
	*x = RemoveAgentRequest{}
	mi := &file_user_agent_user_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentRequest) ProtoMessage() {}

func (x *RemoveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentRequest) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAgentRequest) GetUserAgentId() string {
	if x != nil {
		return x.UserAgentId
	}
	return ""
}

type RemoveAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentResponse) Reset() {
	*x = RemoveAgentResponse{}
	mi := &file_user_agent_user_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentResponse) ProtoMessage() {}

func (x *RemoveAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentResponse.ProtoReflect.Descriptor instead.
func (*RemoveAgentResponse) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateAgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgentId   string                 `protobuf:"bytes,1,opt,name=user_agent_id,json=userAgentId,proto3" json:"user_agent_id,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentConfigRequest) Reset() {
	*x = UpdateAgentConfigRequest{}
	mi := &file_user_agent_user_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentConfigRequest) ProtoMessage() {}

func (x *UpdateAgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAgentConfigRequest) GetUserAgentId() string {
	if x != nil {
		return x.UserAgentId
	}
	return ""
}

func (x *UpdateAgentConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type UpdateAgentConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgentId   string                 `protobuf:"bytes,1,opt,name=user_agent_id,json=userAgentId,proto3" json:"user_agent_id,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentConfigResponse) Reset() {
	*x = UpdateAgentConfigResponse{}
	mi := &file_user_agent_user_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentConfigResponse) ProtoMessage() {}

func (x *UpdateAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_agent_user_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_user_agent_user_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAgentConfigResponse) GetUserAgentId() string {
	if x != nil {
		return x.UserAgentId
	}
	return ""
}

func (x *UpdateAgentConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UpdateAgentConfigResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_user_agent_user_agent_proto protoreflect.FileDescriptor

const file_user_agent_user_agent_proto_rawDesc = "" +
	"\n" +
	"\x1buser_agent/user_agent.proto\x12\x1etrpc.elysia.backend.user_agent\"`\n" +
	"\x12AssignAgentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\"\xa6\x01\n" +
	"\x13AssignAgentResponse\x12\"\n" +
	"\ruser_agent_id\x18\x01 \x01(\tR\vuserAgentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x1f\n" +
	"\vassigned_at\x18\x05 \x01(\tR\n" +
	"assignedAt\"/\n" +
	"\x14GetUserAgentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"g\n" +
	"\x15GetUserAgentsResponse\x12N\n" +
	"\vuser_agents\x18\x01 \x03(\v2-.trpc.elysia.backend.user_agent.UserAgentInfoR\n" +
	"userAgents\"\xec\x01\n" +
	"\rUserAgentInfo\x12\"\n" +
	"\ruser_agent_id\x18\x01 \x01(\tR\vuserAgentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\x12+\n" +
	"\x11agent_description\x18\x05 \x01(\tR\x10agentDescription\x12\x16\n" +
	"\x06config\x18\x06 \x01(\tR\x06config\x12\x1f\n" +
	"\vassigned_at\x18\a \x01(\tR\n" +
	"assignedAt\"8\n" +
	"\x12RemoveAgentRequest\x12\"\n" +
	"\ruser_agent_id\x18\x01 \x01(\tR\vuserAgentId\"/\n" +
	"\x13RemoveAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x18UpdateAgentConfigRequest\x12\"\n" +
	"\ruser_agent_id\x18\x01 \x01(\tR\vuserAgentId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"v\n" +
	"\x19UpdateAgentConfigResponse\x12\"\n" +
	"\ruser_agent_id\x18\x01 \x01(\tR\vuserAgentId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt2\x93\x04\n" +
	"\x10UserAgentService\x12x\n" +
	"\vAssignAgent\x122.trpc.elysia.backend.user_agent.AssignAgentRequest\x1a3.trpc.elysia.backend.user_agent.AssignAgentResponse\"\x00\x12~\n" +
	"\rGetUserAgents\x124.trpc.elysia.backend.user_agent.GetUserAgentsRequest\x1a5.trpc.elysia.backend.user_agent.GetUserAgentsResponse\"\x00\x12x\n" +
	"\vRemoveAgent\x122.trpc.elysia.backend.user_agent.RemoveAgentRequest\x1a3.trpc.elysia.backend.user_agent.RemoveAgentResponse\"\x00\x12\x8a\x01\n" +
	"\x11UpdateAgentConfig\x128.trpc.elysia.backend.user_agent.UpdateAgentConfigRequest\x1a9.trpc.elysia.backend.user_agent.UpdateAgentConfigResponse\"\x00B3Z1github.com/yzf120/elysia-backend/proto/user_agentb\x06proto3"

var (
	file_user_agent_user_agent_proto_rawDescOnce sync.Once
	file_user_agent_user_agent_proto_rawDescData []byte
)

func file_user_agent_user_agent_proto_rawDescGZIP() []byte {
	file_user_agent_user_agent_proto_rawDescOnce.Do(func() {
		file_user_agent_user_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_agent_user_agent_proto_rawDesc), len(file_user_agent_user_agent_proto_rawDesc)))
	})
	return file_user_agent_user_agent_proto_rawDescData
}

var file_user_agent_user_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_agent_user_agent_proto_goTypes = []any{
	(*AssignAgentRequest)(nil),        // 0: trpc.elysia.backend.user_agent.AssignAgentRequest
	(*AssignAgentResponse)(nil),       // 1: trpc.elysia.backend.user_agent.AssignAgentResponse
	(*GetUserAgentsRequest)(nil),      // 2: trpc.elysia.backend.user_agent.GetUserAgentsRequest
	(*GetUserAgentsResponse)(nil),     // 3: trpc.elysia.backend.user_agent.GetUserAgentsResponse
	(*UserAgentInfo)(nil),             // 4: trpc.elysia.backend.user_agent.UserAgentInfo
	(*RemoveAgentRequest)(nil),        // 5: trpc.elysia.backend.user_agent.RemoveAgentRequest
	(*RemoveAgentResponse)(nil),       // 6: trpc.elysia.backend.user_agent.RemoveAgentResponse
	(*UpdateAgentConfigRequest)(nil),  // 7: trpc.elysia.backend.user_agent.UpdateAgentConfigRequest
	(*UpdateAgentConfigResponse)(nil), // 8: trpc.elysia.backend.user_agent.UpdateAgentConfigResponse
}
var file_user_agent_user_agent_proto_depIdxs = []int32{
	4, // 0: trpc.elysia.backend.user_agent.GetUserAgentsResponse.user_agents:type_name -> trpc.elysia.backend.user_agent.UserAgentInfo
	0, // 1: trpc.elysia.backend.user_agent.UserAgentService.AssignAgent:input_type -> trpc.elysia.backend.user_agent.AssignAgentRequest
	2, // 2: trpc.elysia.backend.user_agent.UserAgentService.GetUserAgents:input_type -> trpc.elysia.backend.user_agent.GetUserAgentsRequest
	5, // 3: trpc.elysia.backend.user_agent.UserAgentService.RemoveAgent:input_type -> trpc.elysia.backend.user_agent.RemoveAgentRequest
	7, // 4: trpc.elysia.backend.user_agent.UserAgentService.UpdateAgentConfig:input_type -> trpc.elysia.backend.user_agent.UpdateAgentConfigRequest
	1, // 5: trpc.elysia.backend.user_agent.UserAgentService.AssignAgent:output_type -> trpc.elysia.backend.user_agent.AssignAgentResponse
	3, // 6: trpc.elysia.backend.user_agent.UserAgentService.GetUserAgents:output_type -> trpc.elysia.backend.user_agent.GetUserAgentsResponse
	6, // 7: trpc.elysia.backend.user_agent.UserAgentService.RemoveAgent:output_type -> trpc.elysia.backend.user_agent.RemoveAgentResponse
	8, // 8: trpc.elysia.backend.user_agent.UserAgentService.UpdateAgentConfig:output_type -> trpc.elysia.backend.user_agent.UpdateAgentConfigResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_agent_user_agent_proto_init() }
func file_user_agent_user_agent_proto_init() {
	if File_user_agent_user_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_agent_user_agent_proto_rawDesc), len(file_user_agent_user_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_agent_user_agent_proto_goTypes,
		DependencyIndexes: file_user_agent_user_agent_proto_depIdxs,
		MessageInfos:      file_user_agent_user_agent_proto_msgTypes,
	}.Build()
	File_user_agent_user_agent_proto = out.File
	file_user_agent_user_agent_proto_goTypes = nil
	file_user_agent_user_agent_proto_depIdxs = nil
}
