CREATE TABLE `admin_users` (
                               `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                               `admin_id` varchar(64) NOT NULL COMMENT '管理员唯一标识',
                               `username` varchar(128) NOT NULL COMMENT '登录用户名',
                               `phone_number` varchar(20) DEFAULT NULL COMMENT '手机号',
                               `password` varchar(512) NOT NULL COMMENT '登录密码（密文）',
                               `real_name` varchar(128) NOT NULL COMMENT '真实姓名',
                               `email` varchar(128) NOT NULL COMMENT '邮箱',
                               `role` varchar(32) NOT NULL DEFAULT 'admin' COMMENT '角色标识（默认admin）',
                               `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
                               `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
                               `last_login_ip` varchar(64) DEFAULT NULL COMMENT '最后登录IP',
                               `login_fail_count` int(11) NOT NULL DEFAULT 0 COMMENT '登录失败次数',
                               `password_update_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '密码最后更新时间',
                               `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               `remark` varchar(512) DEFAULT NULL COMMENT '备注信息',
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `idx_admin_id` (`admin_id`),
                               UNIQUE KEY `idx_username` (`username`),
                               UNIQUE KEY `idx_phone_number` (`phone_number`),
                               UNIQUE KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员用户表';