CREATE TABLE IF NOT EXISTS `platform_bookshelf_items` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `item_id` VARCHAR(64) NOT NULL COMMENT '书架条目ID',
    `title` VARCHAR(200) NOT NULL COMMENT '条目标题',
    `description` TEXT COMMENT '文本说明/摘要',
    `content_type` VARCHAR(32) NOT NULL COMMENT '内容类型：text/link/attachment/mixed',
    `external_url` VARCHAR(1024) DEFAULT NULL COMMENT '外部链接',
    `attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '附件原始文件名',
    `attachment_storage_name` VARCHAR(255) DEFAULT NULL COMMENT '附件存储文件名',
    `attachment_mime_type` VARCHAR(128) DEFAULT NULL COMMENT '附件 MIME 类型',
    `attachment_size` BIGINT NOT NULL DEFAULT 0 COMMENT '附件大小（字节）',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值，越大越靠前',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-草稿 1-已发布',
    `creator_admin_id` VARCHAR(64) NOT NULL COMMENT '创建管理员ID',
    `updater_admin_id` VARCHAR(64) NOT NULL COMMENT '最后更新管理员ID',
    `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_item_id` (`item_id`),
    KEY `idx_status_publish_time` (`status`, `publish_time`),
    KEY `idx_content_type` (`content_type`),
    KEY `idx_creator_admin_id` (`creator_admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台书架表';
