CREATE TABLE `user` (
                                  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增id',
                                  `user_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户id',
                                  `user_name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名',
                                  `password`  varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '密码',
                                  `email` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '邮箱',
                                  `gender` int NOT NULL DEFAULT '0' COMMENT '性别',
                                  `phone_number` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '手机号',
                                  `wx_mini_app_open_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '微信小程序端openID',
                                  `chinese_name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '中文姓名',
                                  `risk_level` int NOT NULL DEFAULT '-1' COMMENT '账号风险等级',
                                  `status` int NOT NULL DEFAULT '0' COMMENT '状态, 1 待审批，2 可用，3 驳回， 4 封号',
                                  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
                                  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
                                  `white_list` int NOT NULL DEFAULT '0' COMMENT '白名单标记，0 非白名单，1 封号白名单',
                                  `image_url` varchar(64) NOT NULL DEFAULT '' COMMENT '用户上传头像地址',
                                  `register_source` varchar(32) NOT NULL DEFAULT '' COMMENT '注册来源phone, miniprogram, manual',
                                  `user_type` varchar(32) NOT NULL DEFAULT '' COMMENT '用户类型',
                                  PRIMARY KEY (`id`),
                                  UNIQUE KEY `uk_user_id` (`user_id`),
                                  UNIQUE KEY `uk_phone_number` (`phone_number`),
                                  KEY `idx_wx_mini_app_open_id` (`wx_mini_app_open_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户注册信息表'