// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user/user.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // 用户ID
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // 用户名
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                  // 邮箱
	Gender          int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                               // 性别 0-未知 1-男 2-女
	PhoneNumber     string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                   // 手机号
	WxMiniAppOpenId string                 `protobuf:"bytes,6,opt,name=wx_mini_app_open_id,json=wxMiniAppOpenId,proto3" json:"wx_mini_app_open_id,omitempty"` // 微信小程序openID
	ChineseName     string                 `protobuf:"bytes,7,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`                   // 中文姓名
	RiskLevel       int32                  `protobuf:"varint,8,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`                        // 账号风险等级
	Status          int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                               // 状态 1-待审批 2-可用 3-驳回 4-封号
	CreateTime      string                 `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                     // 创建时间
	UpdateTime      string                 `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                     // 更新时间
	ImageUrl        string                 `protobuf:"bytes,12,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                           // 用户头像地址
	RegisterSource  string                 `protobuf:"bytes,13,opt,name=register_source,json=registerSource,proto3" json:"register_source,omitempty"`         // 注册来源 phone/miniprogram/manual
	UserType        string                 `protobuf:"bytes,14,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                           // 用户类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetWxMiniAppOpenId() string {
	if x != nil {
		return x.WxMiniAppOpenId
	}
	return ""
}

func (x *User) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

func (x *User) GetRiskLevel() int32 {
	if x != nil {
		return x.RiskLevel
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *User) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *User) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *User) GetRegisterSource() string {
	if x != nil {
		return x.RegisterSource
	}
	return ""
}

func (x *User) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 创建用户请求
type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserName        string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // 用户名（必填）
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                            // 密码（必填）
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                  // 邮箱（可选）
	Gender          int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                               // 性别（可选）
	PhoneNumber     string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                   // 手机号（必填，用于注册）
	WxMiniAppOpenId string                 `protobuf:"bytes,6,opt,name=wx_mini_app_open_id,json=wxMiniAppOpenId,proto3" json:"wx_mini_app_open_id,omitempty"` // 微信小程序openID（可选）
	ChineseName     string                 `protobuf:"bytes,7,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`                   // 中文姓名（可选）
	ImageUrl        string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                            // 用户头像地址（可选）
	RegisterSource  string                 `protobuf:"bytes,9,opt,name=register_source,json=registerSource,proto3" json:"register_source,omitempty"`          // 注册来源（必填）
	UserType        string                 `protobuf:"bytes,10,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                           // 用户类型（可选）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetWxMiniAppOpenId() string {
	if x != nil {
		return x.WxMiniAppOpenId
	}
	return ""
}

func (x *CreateUserRequest) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

func (x *CreateUserRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateUserRequest) GetRegisterSource() string {
	if x != nil {
		return x.RegisterSource
	}
	return ""
}

func (x *CreateUserRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 创建用户响应
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码 0-成功 其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 创建的用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 获取用户请求
type GetUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // 用户ID（三选一）
	PhoneNumber     string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                   // 手机号（三选一）
	WxMiniAppOpenId string                 `protobuf:"bytes,3,opt,name=wx_mini_app_open_id,json=wxMiniAppOpenId,proto3" json:"wx_mini_app_open_id,omitempty"` // 微信小程序openID（三选一）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetUserRequest) GetWxMiniAppOpenId() string {
	if x != nil {
		return x.WxMiniAppOpenId
	}
	return ""
}

// 获取用户响应
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码 0-成功 其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 更新用户请求
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID（必填）
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`          // 用户名（可选）
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                // 邮箱（可选）
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                             // 性别（可选）
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 手机号（可选）
	ChineseName   string                 `protobuf:"bytes,6,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"` // 中文姓名（可选）
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                             // 状态（可选）
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`          // 用户头像地址（可选）
	UserType      string                 `protobuf:"bytes,9,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`          // 用户类型（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 更新用户响应
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码 0-成功 其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 更新后的用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 删除用户请求
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 删除用户响应
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 响应码 0-成功 其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询用户列表请求
type ListUsersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                          // 页码（从1开始）
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                  // 每页数量
	Status         int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                      // 状态筛选（可选）
	RegisterSource string                 `protobuf:"bytes,4,opt,name=register_source,json=registerSource,proto3" json:"register_source,omitempty"` // 注册来源筛选（可选）
	UserType       string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`                   // 用户类型筛选（可选）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUsersRequest) GetRegisterSource() string {
	if x != nil {
		return x.RegisterSource
	}
	return ""
}

func (x *ListUsersRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 查询用户列表响应
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                         // 响应码 0-成功 其他-失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                    // 响应消息
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`                        // 用户列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListUsersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x18trpc.elysia.backend.user\"\xba\x03\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12,\n" +
	"\x13wx_mini_app_open_id\x18\x06 \x01(\tR\x0fwxMiniAppOpenId\x12!\n" +
	"\fchinese_name\x18\a \x01(\tR\vchineseName\x12\x1d\n" +
	"\n" +
	"risk_level\x18\b \x01(\x05R\triskLevel\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\v \x01(\tR\n" +
	"updateTime\x12\x1b\n" +
	"\timage_url\x18\f \x01(\tR\bimageUrl\x12'\n" +
	"\x0fregister_source\x18\r \x01(\tR\x0eregisterSource\x12\x1b\n" +
	"\tuser_type\x18\x0e \x01(\tR\buserType\"\xd1\x02\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12,\n" +
	"\x13wx_mini_app_open_id\x18\x06 \x01(\tR\x0fwxMiniAppOpenId\x12!\n" +
	"\fchinese_name\x18\a \x01(\tR\vchineseName\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12'\n" +
	"\x0fregister_source\x18\t \x01(\tR\x0eregisterSource\x12\x1b\n" +
	"\tuser_type\x18\n" +
	" \x01(\tR\buserType\"v\n" +
	"\x12CreateUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04user\x18\x03 \x01(\v2\x1e.trpc.elysia.backend.user.UserR\x04user\"z\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12,\n" +
	"\x13wx_mini_app_open_id\x18\x03 \x01(\tR\x0fwxMiniAppOpenId\"s\n" +
	"\x0fGetUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04user\x18\x03 \x01(\v2\x1e.trpc.elysia.backend.user.UserR\x04user\"\x8f\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12!\n" +
	"\fchinese_name\x18\x06 \x01(\tR\vchineseName\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tuser_type\x18\t \x01(\tR\buserType\"v\n" +
	"\x12UpdateUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04user\x18\x03 \x01(\v2\x1e.trpc.elysia.backend.user.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x12DeleteUserResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12'\n" +
	"\x0fregister_source\x18\x04 \x01(\tR\x0eregisterSource\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\"\xbe\x01\n" +
	"\x11ListUsersResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x05users\x18\x03 \x03(\v2\x1e.trpc.elysia.backend.user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize2\x98\x04\n" +
	"\vUserService\x12i\n" +
	"\n" +
	"CreateUser\x12+.trpc.elysia.backend.user.CreateUserRequest\x1a,.trpc.elysia.backend.user.CreateUserResponse\"\x00\x12`\n" +
	"\aGetUser\x12(.trpc.elysia.backend.user.GetUserRequest\x1a).trpc.elysia.backend.user.GetUserResponse\"\x00\x12i\n" +
	"\n" +
	"UpdateUser\x12+.trpc.elysia.backend.user.UpdateUserRequest\x1a,.trpc.elysia.backend.user.UpdateUserResponse\"\x00\x12i\n" +
	"\n" +
	"DeleteUser\x12+.trpc.elysia.backend.user.DeleteUserRequest\x1a,.trpc.elysia.backend.user.DeleteUserResponse\"\x00\x12f\n" +
	"\tListUsers\x12*.trpc.elysia.backend.user.ListUsersRequest\x1a+.trpc.elysia.backend.user.ListUsersResponse\"\x00B-Z+github.com/yzf120/elysia-backend/proto/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_user_proto_goTypes = []any{
	(*User)(nil),               // 0: trpc.elysia.backend.user.User
	(*CreateUserRequest)(nil),  // 1: trpc.elysia.backend.user.CreateUserRequest
	(*CreateUserResponse)(nil), // 2: trpc.elysia.backend.user.CreateUserResponse
	(*GetUserRequest)(nil),     // 3: trpc.elysia.backend.user.GetUserRequest
	(*GetUserResponse)(nil),    // 4: trpc.elysia.backend.user.GetUserResponse
	(*UpdateUserRequest)(nil),  // 5: trpc.elysia.backend.user.UpdateUserRequest
	(*UpdateUserResponse)(nil), // 6: trpc.elysia.backend.user.UpdateUserResponse
	(*DeleteUserRequest)(nil),  // 7: trpc.elysia.backend.user.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 8: trpc.elysia.backend.user.DeleteUserResponse
	(*ListUsersRequest)(nil),   // 9: trpc.elysia.backend.user.ListUsersRequest
	(*ListUsersResponse)(nil),  // 10: trpc.elysia.backend.user.ListUsersResponse
}
var file_user_user_proto_depIdxs = []int32{
	0,  // 0: trpc.elysia.backend.user.CreateUserResponse.user:type_name -> trpc.elysia.backend.user.User
	0,  // 1: trpc.elysia.backend.user.GetUserResponse.user:type_name -> trpc.elysia.backend.user.User
	0,  // 2: trpc.elysia.backend.user.UpdateUserResponse.user:type_name -> trpc.elysia.backend.user.User
	0,  // 3: trpc.elysia.backend.user.ListUsersResponse.users:type_name -> trpc.elysia.backend.user.User
	1,  // 4: trpc.elysia.backend.user.UserService.CreateUser:input_type -> trpc.elysia.backend.user.CreateUserRequest
	3,  // 5: trpc.elysia.backend.user.UserService.GetUser:input_type -> trpc.elysia.backend.user.GetUserRequest
	5,  // 6: trpc.elysia.backend.user.UserService.UpdateUser:input_type -> trpc.elysia.backend.user.UpdateUserRequest
	7,  // 7: trpc.elysia.backend.user.UserService.DeleteUser:input_type -> trpc.elysia.backend.user.DeleteUserRequest
	9,  // 8: trpc.elysia.backend.user.UserService.ListUsers:input_type -> trpc.elysia.backend.user.ListUsersRequest
	2,  // 9: trpc.elysia.backend.user.UserService.CreateUser:output_type -> trpc.elysia.backend.user.CreateUserResponse
	4,  // 10: trpc.elysia.backend.user.UserService.GetUser:output_type -> trpc.elysia.backend.user.GetUserResponse
	6,  // 11: trpc.elysia.backend.user.UserService.UpdateUser:output_type -> trpc.elysia.backend.user.UpdateUserResponse
	8,  // 12: trpc.elysia.backend.user.UserService.DeleteUser:output_type -> trpc.elysia.backend.user.DeleteUserResponse
	10, // 13: trpc.elysia.backend.user.UserService.ListUsers:output_type -> trpc.elysia.backend.user.ListUsersResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
