// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: user/user.proto

package user

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// UserServiceService defines service.
type UserServiceService interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)

	GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error)

	UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error)

	DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error)

	ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error)
}

func UserServiceService_CreateUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).CreateUser(ctx, reqbody.(*CreateUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserServiceService_GetUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).GetUser(ctx, reqbody.(*GetUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserServiceService_UpdateUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).UpdateUser(ctx, reqbody.(*UpdateUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserServiceService_DeleteUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).DeleteUser(ctx, reqbody.(*DeleteUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserServiceService_ListUsers_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListUsersRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).ListUsers(ctx, reqbody.(*ListUsersRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// UserServiceServer_ServiceDesc descriptor for server.RegisterService.
var UserServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.user.UserService",
	HandlerType: ((*UserServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.user.UserService/CreateUser",
			Func: UserServiceService_CreateUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user.UserService/GetUser",
			Func: UserServiceService_GetUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user.UserService/UpdateUser",
			Func: UserServiceService_UpdateUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user.UserService/DeleteUser",
			Func: UserServiceService_DeleteUser_Handler,
		},
		{
			Name: "/trpc.elysia.backend.user.UserService/ListUsers",
			Func: UserServiceService_ListUsers_Handler,
		},
	},
}

// RegisterUserServiceService registers service.
func RegisterUserServiceService(s server.Service, svr UserServiceService) {
	if err := s.Register(&UserServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("UserService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedUserService struct{}

func (s *UnimplementedUserService) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, errors.New("rpc CreateUser of service UserService is not implemented")
}
func (s *UnimplementedUserService) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, errors.New("rpc GetUser of service UserService is not implemented")
}
func (s *UnimplementedUserService) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, errors.New("rpc UpdateUser of service UserService is not implemented")
}
func (s *UnimplementedUserService) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, errors.New("rpc DeleteUser of service UserService is not implemented")
}
func (s *UnimplementedUserService) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, errors.New("rpc ListUsers of service UserService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// UserServiceClientProxy defines service client proxy
type UserServiceClientProxy interface {
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...client.Option) (rsp *CreateUserResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest, opts ...client.Option) (rsp *GetUserResponse, err error)

	UpdateUser(ctx context.Context, req *UpdateUserRequest, opts ...client.Option) (rsp *UpdateUserResponse, err error)

	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...client.Option) (rsp *DeleteUserResponse, err error)

	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...client.Option) (rsp *ListUsersResponse, err error)
}

type UserServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewUserServiceClientProxy = func(opts ...client.Option) UserServiceClientProxy {
	return &UserServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *UserServiceClientProxyImpl) CreateUser(ctx context.Context, req *CreateUserRequest, opts ...client.Option) (*CreateUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user.UserService/CreateUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("CreateUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserServiceClientProxyImpl) GetUser(ctx context.Context, req *GetUserRequest, opts ...client.Option) (*GetUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user.UserService/GetUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("GetUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserServiceClientProxyImpl) UpdateUser(ctx context.Context, req *UpdateUserRequest, opts ...client.Option) (*UpdateUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user.UserService/UpdateUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("UpdateUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserServiceClientProxyImpl) DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...client.Option) (*DeleteUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user.UserService/DeleteUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("DeleteUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserServiceClientProxyImpl) ListUsers(ctx context.Context, req *ListUsersRequest, opts ...client.Option) (*ListUsersResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.user.UserService/ListUsers")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("ListUsers")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListUsersResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
