// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: conversation/conversation.proto

package conversation

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ConversationServiceService defines service.
type ConversationServiceService interface {
	CreateConversation(ctx context.Context, req *CreateConversationRequest) (*CreateConversationResponse, error)

	GetConversation(ctx context.Context, req *GetConversationRequest) (*GetConversationResponse, error)

	SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error)
}

func ConversationServiceService_CreateConversation_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateConversationRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConversationServiceService).CreateConversation(ctx, reqbody.(*CreateConversationRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConversationServiceService_GetConversation_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetConversationRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConversationServiceService).GetConversation(ctx, reqbody.(*GetConversationRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ConversationServiceService_SendMessage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SendMessageRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ConversationServiceService).SendMessage(ctx, reqbody.(*SendMessageRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ConversationServiceServer_ServiceDesc descriptor for server.RegisterService.
var ConversationServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.backend.conversation.ConversationService",
	HandlerType: ((*ConversationServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.backend.conversation.ConversationService/CreateConversation",
			Func: ConversationServiceService_CreateConversation_Handler,
		},
		{
			Name: "/trpc.elysia.backend.conversation.ConversationService/GetConversation",
			Func: ConversationServiceService_GetConversation_Handler,
		},
		{
			Name: "/trpc.elysia.backend.conversation.ConversationService/SendMessage",
			Func: ConversationServiceService_SendMessage_Handler,
		},
	},
}

// RegisterConversationServiceService registers service.
func RegisterConversationServiceService(s server.Service, svr ConversationServiceService) {
	if err := s.Register(&ConversationServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ConversationService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedConversationService struct{}

func (s *UnimplementedConversationService) CreateConversation(ctx context.Context, req *CreateConversationRequest) (*CreateConversationResponse, error) {
	return nil, errors.New("rpc CreateConversation of service ConversationService is not implemented")
}
func (s *UnimplementedConversationService) GetConversation(ctx context.Context, req *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, errors.New("rpc GetConversation of service ConversationService is not implemented")
}
func (s *UnimplementedConversationService) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, errors.New("rpc SendMessage of service ConversationService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ConversationServiceClientProxy defines service client proxy
type ConversationServiceClientProxy interface {
	CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...client.Option) (rsp *CreateConversationResponse, err error)

	GetConversation(ctx context.Context, req *GetConversationRequest, opts ...client.Option) (rsp *GetConversationResponse, err error)

	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...client.Option) (rsp *SendMessageResponse, err error)
}

type ConversationServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewConversationServiceClientProxy = func(opts ...client.Option) ConversationServiceClientProxy {
	return &ConversationServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ConversationServiceClientProxyImpl) CreateConversation(ctx context.Context, req *CreateConversationRequest, opts ...client.Option) (*CreateConversationResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.conversation.ConversationService/CreateConversation")
	msg.WithCalleeServiceName(ConversationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConversationService")
	msg.WithCalleeMethod("CreateConversation")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateConversationResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConversationServiceClientProxyImpl) GetConversation(ctx context.Context, req *GetConversationRequest, opts ...client.Option) (*GetConversationResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.conversation.ConversationService/GetConversation")
	msg.WithCalleeServiceName(ConversationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConversationService")
	msg.WithCalleeMethod("GetConversation")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetConversationResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ConversationServiceClientProxyImpl) SendMessage(ctx context.Context, req *SendMessageRequest, opts ...client.Option) (*SendMessageResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.backend.conversation.ConversationService/SendMessage")
	msg.WithCalleeServiceName(ConversationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ConversationService")
	msg.WithCalleeMethod("SendMessage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SendMessageResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
